# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
    push:
    pull_request:
    workflow_dispatch:
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest
                cfg:
                    - Debug
                    - Release
        runs-on: ${{ matrix.os }}
        steps:
            - name: Clone repository
              uses: actions/checkout@v3.0.2
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Set up .NET
              uses: actions/setup-dotnet@v2.1.0
            - name: Build project
              run: |
                  dotnet tool restore
                  dotnet publish -c ${{ matrix.cfg }}
            - name: Run tests
              run: |
                  dotnet test -c ${{ matrix.cfg }} --no-build
