# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Package
on:
    push:
        branches:
            - master
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
    package:
        if: github.repository == 'vezel-dev/celerity'
        runs-on: windows-2022
        steps:
            - name: Clone repository
              uses: actions/checkout@v3.5.2
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Set up .NET
              uses: actions/setup-dotnet@v3.0.3
            - uses: actions/setup-node@v3.6.0
              with:
                  node-version-file: package.json
            - name: Run Cake
              run: |
                  ./cake upload-dotnet-github
            - name: Upload artifacts
              if: always()
              uses: actions/upload-artifact@v3.1.2
              with:
                  name: ${{ github.workflow }}-${{ github.run_number }}-${{ github.run_attempt }}-windows-2022-Debug
                  path: |
                      out/bin/*
                      out/bld/*
                      out/log/*
                      out/pkg/*
                      out/pub/*
                      out/trx/*
            - name: Prune GitHub packages
              uses: SmartsquareGmbH/delete-old-packages@v0.6.0
              with:
                  names: |
                      celerity
                      Vezel.Celerity.Common
                      Vezel.Celerity.Language
                      Vezel.Celerity.Language.Library
                      Vezel.Celerity.Language.Service
                      Vezel.Celerity.Language.Tooling
                      Vezel.Celerity.Runtime
                      Vezel.Celerity.Runtime.Compiler
                      Vezel.Celerity.Runtime.Interpreter
                      Vezel.Celerity.Runtime.Kernel
                  keep: 25
