# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release
on:
    release:
        types:
            - published
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
    NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
    VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
jobs:
    release:
        if: github.repository == 'vezel-dev/celerity'
        runs-on: windows-2022
        steps:
            - name: Clone repository
              uses: actions/checkout@v3.5.3
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Set up .NET
              uses: actions/setup-dotnet@v3.2.0
            - name: Set up Node.js
              uses: actions/setup-node@v3.7.0
              with:
                  node-version-file: src/extensions/vscode/package.json
            - name: Run Cake
              run: |
                  ./cake upload-core-nuget -c Release
                  ./cake upload-vscode-vsce -c Release
                  ./cake upload-vscode-ovsx -c Release
            - name: Upload artifacts
              if: always()
              uses: actions/upload-artifact@v3.1.2
              with:
                  name: ${{ github.workflow }}-${{ github.run_number }}-${{ github.run_attempt }}-windows-2022-Release
                  path: |
                      out/log
                      out/pkg
                      out/pub
                      out/trx
